CREATE TABLE stocks  (
    id Bigserial PRIMARY KEY NOT NULL,
    SYMBOL VARCHAR(20) NOT NULL,
    OPEN_PRICE DOUBLE PRECISION NOT NULL,
    CLOSE_PRICE DOUBLE PRECISION NOT NULL,
    DATE_OF_RECORD VARCHAR(20) NOT NULL
);
